let cem = [
  {
    id: "B39FBA1C78F0C97D",
    name: "Itaú Imobiliario",
    client_code: "7021",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 14,
    associated_user: null,
  },
  {
    id: "9CEEB1359860A0B3",
    name: "Itaú PJ",
    client_code: "57",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1039,
    associated_user: null,
  },
  {
    id: "22B016CA1CF2A324",
    name: "Itaú Veiculos 2",
    client_code: "7050",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 34,
    associated_user: null,
  },
  {
    id: "2E857E705BEDCDBE",
    name: "Carteiro Itaú PF",
    client_code: "7022",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "1BC4AB9886644E36",
    name: "Carteiro Itaú PF Colchão",
    client_code: "7023",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 108,
    associated_user: null,
  },
  {
    id: "7532AC2EE99D00EC",
    name: "Carteiro Itaú Cartões Colchão",
    client_code: "7025",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 338,
    associated_user: null,
  },
  {
    id: "1B35FDCAAA610DFC",
    name: "Carteiro Recovery",
    client_code: "7045",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "6D43989540114DE7",
    name: "Carteiro Volkswagen",
    client_code: "7088",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "1B42550CDB34BF33",
    name: "Carteiro PAN - RETOMADOS",
    client_code: "7047",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "C8C8A00C7B07C1AF",
    name: "Carteiro PAN - VAREJO",
    client_code: "7048",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "A6D7EE89F472CFE2",
    name: "Carteiro PAN ATIVOS - COBRANÇA",
    client_code: "7049",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "4F6059B3B47DF5F6",
    name: "Carteiro Pan Encerramentos",
    client_code: "7096",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "9609B4C6CE4582AE",
    name: "Carteiro Pan Cartões 2.0",
    client_code: "7051",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "5EC021C2CFC08822",
    name: "Carteiro PAN WO - COBRANÇA",
    client_code: "7052",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 2,
    associated_user: null,
  },
  {
    id: "7314B6F3D7D4F687",
    name: "Carteiro PAN AJUIZADOS - COBRANÇA",
    client_code: "7053",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "DFFC16847B9456B1",
    name: "Carteiro PAN - CONTACT",
    client_code: "7054",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "D768C8A02F51C203",
    name: "Carteiro Pan Imobiliário",
    client_code: "7055",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "3E6F529849E85FDA",
    name: "Carteiro Pan Consórcio",
    client_code: "7056",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "DD92D04E14AE42D2",
    name: "Carteiro Pan Cartões",
    client_code: "7057",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "C4E7CC55D27C2D82",
    name: "Carteiro Pan Cartão Ativo ",
    client_code: "7058",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "F84F9C89556F7C8A",
    name: "Carteiro Pan Limite Emergencial",
    client_code: "7059",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "C963DA98D7C1A22E",
    name: "Carteiro Pan Emprestimo Pessoal",
    client_code: "7060",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "9196162DC1976F75",
    name: "Carteiro Safra",
    client_code: "7061",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1,
    associated_user: null,
  },
  {
    id: "529BC4A26BDBB28D",
    name: "Carteiro Safra Veículos",
    client_code: "7062",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "40243C6D2E6A3A69",
    name: "Carteiro Safra Refin",
    client_code: "7063",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "1130882349051DD6",
    name: "BV Juridico Contencioso IPF 2",
    client_code: "7089",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "D654AE21B3166122",
    name: "BV Juridico Contencioso IPF 3",
    client_code: "7091",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "A228842638E689A3",
    name: "BV Juridico Contencioso IPF 4",
    client_code: "7094",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "A268C9A166B175F7",
    name: "BV WO 1",
    client_code: "7097",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1,
    associated_user: null,
  },
  {
    id: "679D02A77FA4E99E",
    name: "BV WO 2",
    client_code: "7098",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1,
    associated_user: null,
  },

  {
    id: "07F4ED83DE2102F0",
    name: "BV WO 3",
    client_code: "7100",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "120D18A8F4817467",
    name: "BV WO 4",
    client_code: "7101",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "82D8653C9AD89CDE",
    name: "TesteMassivoAPI",
    client_code: "TesteMassivoAPI",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "00C8C09A0CC166DA",
    name: "BV Bom Pagador",
    client_code: "7011",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 17333,
    associated_user: null,
  },
  {
    id: "65B7600E4461D2ED",
    name: "BV ADM",
    client_code: "7012",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 7171,
    associated_user: null,
  },
  {
    id: "AE1B2230C4E3479E",
    name: "BV ADM Reneg",
    client_code: "7013",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 5472,
    associated_user: null,
  },
  {
    id: "BC6FEDED863810D3",
    name: "Teste Ivan",
    client_code: "",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "06F7F0A883CC4994",
    name: "Carteiro Safra BS Grupo 2",
    client_code: "7064",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "FB98F0A117EFF8F3",
    name: "Carteiro Safra BS Grupo 1",
    client_code: "7065",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "C86D7AB95E8B630B",
    name: "Carteiro Safra Saldo Remanescente",
    client_code: "7066",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "B5165763EA7D3743",
    name: "Carteiro SAFRA CARTÕES - VAREJO",
    client_code: "7067",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "B6D3D758FE01F290",
    name: "Carteiro Porto Seguro",
    client_code: "7068",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "98F6EEA55D01ADC2",
    name: "Carteiro Inter",
    client_code: "7069",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "6099786721673874",
    name: "Carteiro BMG",
    client_code: "7070",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "BE6458882281A828",
    name: "Carteiro BANCO DO BRASIL - VEÍCULOS",
    client_code: "7071",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },

  {
    id: "5E872A38986D22AD",
    name: "Carteiro PICPAY - VAREJO",
    client_code: "7072",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "1B464407E2C39744",
    name: "Carteiro ARC4U - SECURITIZADORA",
    client_code: "7073",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "77A7CB40D1B0C429",
    name: "Carteiro MAGALU - VAREJO",
    client_code: "7074",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "5AFF3A2E4058CD1A",
    name: "Carteiro MÉLIUZ - VAREJO",
    client_code: "7075",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "ACCC3E2DFBB0F039",
    name: "Carteiro RENNER - VAREJO",
    client_code: "7076",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "9C87C8D17E7FF90F",
    name: "Carteiro RETURN - SECURITIZADORA",
    client_code: "7077",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "AED3089A16C866F2",
    name: "Carteiro VIA VAREJO",
    client_code: "7078",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "6CA19FCE423AAE83",
    name: "Carteiro DIVZERO - SECURITIZADORA",
    client_code: "7079",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "3BA3DD575C59C3EC",
    name: "Carteiro ITAPEVA - SECURITIZADORA",
    client_code: "7080",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "F20A60377CA282F7",
    name: "Carteiro CETELEM - VAREJO",
    client_code: "7081",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "D10B361D1CACB565",
    name: "Carteiro Mercantil",
    client_code: "7082",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "4A56B3A0F7F62161",
    name: "BV CARTÕES AMIGÁVEL - VAREJO",
    client_code: "165",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 70,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "2DBB5FEFE43468B0",
    name: "C6 BANK - VEÍCULOS",
    client_code: "100",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 70,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "730D81C464C317A6",
    name: "Carteiro Itaú Cartões",
    client_code: "7014",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 13183,
    associated_user: null,
  },
  {
    id: "F8B92F387FC36C79",
    name: "Itaú PF Portal",
    client_code: "7016",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 2,
    associated_user: null,
  },

  {
    id: "A8649A1C34581D02",
    name: "Itaú Cartões Portal",
    client_code: "7017",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "4C9BDB91AF0504CB",
    name: "Itaú Phygital Portal",
    client_code: "7018",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "8A80865830C21E76",
    name: "BV Bom Pagador 2",
    client_code: "7037",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 5926,
    associated_user: null,
  },
  {
    id: "AB5422E793C54D17",
    name: "BV ADM 2",
    client_code: "7092",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 2914,
    associated_user: null,
  },
  {
    id: "EB091C17E0278FF8",
    name: "BV ADM Reneg 2",
    client_code: "7090",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 141,
    associated_user: null,
  },
  {
    id: "74ECFE4B90F2C536",
    name: "Itaú Veiculos",
    client_code: "30",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1345,
    associated_user: null,
  },
  {
    id: "AB6595C81CFED4BB",
    name: "Carteiro Itaú Phygital BPF",
    client_code: "7026",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "4268CB7A96295AD6",
    name: "Carteiro Itaú PJ",
    client_code: "7027",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1,
    associated_user: null,
  },
  {
    id: "927C5F485CAA17D9",
    name: "Carteiro Itaú Veículos",
    client_code: "7028",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "06676EAA7910CF6D",
    name: "Carteiro Itaú Imobiliário",
    client_code: "7029",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "0BCE91C558A4E086",
    name: "Carteiro Itaú IC",
    client_code: "7030",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "FFEC6DAE5C1DB601",
    name: "Carteiro Itaú CDC",
    client_code: "7031",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "BAADB6B52F61EC02",
    name: "Carteiro Itaú Personnalite",
    client_code: "7032",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "7C59CDB504181827",
    name: "Carteiro Bradesco Comercial",
    client_code: "7033",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "1A32607370441582",
    name: "Carteiro Bradesco Comercial",
    client_code: "7033",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "1B0602A0075C8482",
    name: "Carteiro Bradesco Digital",
    client_code: "7034",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "0893EE7E73AF65DC",
    name: "Carteiro Bradesco Veículos",
    client_code: "7035",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "184A465E82C0829A",
    name: "Carteiro Bradesco LP",
    client_code: "7036",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "F5F6FA66DE8E4A91",
    name: "Carteiro Bradesco Telecobranca",
    client_code: "7037",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "B4D9B7DAAD8EC68E",
    name: "Carteiro BRADESCO - ALTOS VALORES",
    client_code: "7083",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "5320EAAE84DB9AE9",
    name: "Carteiro NUBANK ATIVO - VAREJO",
    client_code: "7040",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 463,
    associated_user: null,
  },
  {
    id: "10DA92C9E133E2C7",
    name: "Carteiro NUBANK DI - VAREJO",
    client_code: "7041",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "B88E5BFFA472886D",
    name: "Carteiro NUBANK EMPRÉSTIMOS - VAREJO",
    client_code: "7084",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "F57FFAE8934ABF43",
    name: "Carteiro SANTANDER - FINANCEIRA",
    client_code: "7086",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "8474047ACA81CAC6",
    name: "Carteiro C6 Bank",
    client_code: "7043",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "3A28D6480385C557",
    name: "Carteiro C6 Auto",
    client_code: "7087",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "1D58A671C2A0B397",
    name: "Itaú ACC",
    client_code: "7005",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 70,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 10507,
    associated_user: null,
  },
  {
    id: "A55F764ED661A4F3",
    name: "BV Juridico Contencioso IPF 1",
    client_code: "7046",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1,
    associated_user: null,
  },
  {
    id: "BD22788BD2927404",
    name: "Carteiro BV WO",
    client_code: "6008",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "5D107DC8D09B23DB",
    name: "AGV - Nubank",
    client_code: "7038",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 13,
    associated_user: null,
  },
  {
    id: "8883EE021246655A",
    name: "Carteiro BV Bom Pagador",
    client_code: "6001",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 215,
    associated_user: null,
  },
  {
    id: "A4C057CC48F81112",
    name: "Carteiro BV Reneg ADM",
    client_code: "6003",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 489,
    associated_user: null,
  },
  {
    id: "4DEBD0CBB5C861CB",
    name: "Santander - Financeira",
    client_code: "7015",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 156,
    associated_user: null,
  },
  {
    id: "9E7BFC879AC9CA43",
    name: "Carteiro Santander Financeira",
    client_code: "7019",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 39,
    associated_user: null,
  },
  {
    id: "DA7D9AA96D4636C2",
    name: "Itaú Personnalite",
    client_code: "7020",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1725,
    associated_user: null,
  },
  {
    id: "08EF73F913768414",
    name: "Itaú PF 2",
    client_code: "7085",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 5689,
    associated_user: null,
  },
  {
    id: "26966B2C6AA7603F",
    name: "Carteiro BVCL",
    client_code: "6004",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "8C1EC770BFC67EE4",
    name: "Carteiro BV CA",
    client_code: "6005",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "764EE9A7C1B4A67B",
    name: "Carteiro BV CP",
    client_code: "6006",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "C7749E0EEE63C2DA",
    name: "Carteiro BV Juridico Contencioso IPF",
    client_code: "6007",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "1715AC5DE14EB1B2",
    name: "Carteiro BV NEON",
    client_code: "6009",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "ECD9880D622F111C",
    name: "Carteiro BV Solar ",
    client_code: "6010",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "DF6E9BD31D6C53D8",
    name: "Carteiro BV CONSIGNADO - VAREJO",
    client_code: "6011",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "7DA5676A4035AFD9",
    name: "Carteiro BV - DESAVERBADO",
    client_code: "6012",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "A6BF9B4B9E1D03A1",
    name: "Chatbot",
    client_code: "97999",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 690028,
    associated_user: null,
  },
  
  {
    id: "FF2F741E013C013C",
    name: "BV CL - VAREJO",
    client_code: "02",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "11D58B5EC37F3B86",
    name: "Mask Comunicado BV",
    client_code: "BV_COMUNICADO_BL",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: null,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 150220,
    associated_user: null,
  },
  {
    id: "9159308D649E6A51",
    name: "Carteiro BV ADM",
    client_code: "6002",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 21264,
    associated_user: null,
  },
  {
    id: "439F862A2B115928",
    name: "Itaú PF",
    client_code: "7004",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 29786,
    associated_user: null,
  },
  {
    id: "C3668AC366C19F55",
    name: "Itaú PF 3",
    client_code: "7042",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1017,
    associated_user: null,
  },
  {
    id: "DA3A3242975CC5A7",
    name: "Itaú PF 4",
    client_code: "7043",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 6408,
    associated_user: null,
  },
  {
    id: "DD46FADFC45EC419",
    name: "Itaú PF 5",
    client_code: "7044",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 8669,
    associated_user: null,
  },
  {
    id: "A29B7C5A6265DB28",
    name: "Itaú ACC 2",
    client_code: "7093",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 70,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 5534,
    associated_user: null,
  },
  {
    id: "279D375B1F94AE37",
    name: "Itaú ACC 3",
    client_code: "7095",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 70,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 7034,
    associated_user: null,
  },
  {
    id: "058D21852D21B1CD",
    name: "Itaú ACC 5",
    client_code: "7098",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 70,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1430,
    associated_user: null,
  },
  {
    id: "D083142DF80F8C56",
    name: "Itaú ACC 4",
    client_code: "7099",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 70,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 2204,
    associated_user: null,
  },
  {
    id: "CF04D2E46FD601C1",
    name: "Itaú Phygital PF",
    client_code: "7006",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: 15,
    number_loyal_customers_offline: 8,
    term_Idr: "",
    idr_return_time: 70,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 2,
    associated_user: null,
  },
  {
    id: "5FEED030FC836E35",
    name: "BV - SOLAR",
    client_code: "18",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1,
    associated_user: null,
  },
];
for (let i = 0; i < cem.length; i++) {
  const element = cem[i];
  console.log(`${cem[i].name};${cem[i].client_code}`);
}
