let Robbu = [
  {
    id: "439F862A2B115928",
    name: "Itaú PF",
    client_code: "7004",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 29744,
    associated_user: null,
  },
  {
    id: "11D58B5EC37F3B86",
    name: "Mask Comunicado BV",
    client_code: "BV_COMUNICADO_BL",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: null,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 148515,
    associated_user: null,
  },
  {
    id: "9159308D649E6A51",
    name: "Carteiro BV ADM",
    client_code: "6002",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 21934,
    associated_user: null,
  },
  {
    id: "A6BF9B4B9E1D03A1",
    name: "Chatbot",
    client_code: "97999",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 705598,
    associated_user: null,
  },
  {
    id: "FF2F741E013C013C",
    name: "BV CL - VAREJO",
    client_code: "02",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "CF04D2E46FD601C1",
    name: "Itaú Phygital PF",
    client_code: "7006",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: 15,
    number_loyal_customers_offline: 8,
    term_Idr: "",
    idr_return_time: 70,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 2,
    associated_user: null,
  },
  {
    id: "1D58A671C2A0B397",
    name: "Itaú ACC",
    client_code: "7005",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 70,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 10391,
    associated_user: null,
  },
  {
    id: "4A56B3A0F7F62161",
    name: "BV CARTÕES AMIGÁVEL - VAREJO",
    client_code: "165",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 70,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "2DBB5FEFE43468B0",
    name: "C6 BANK - VEÍCULOS",
    client_code: "100",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 70,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "5FEED030FC836E35",
    name: "BV - SOLAR",
    client_code: "18",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1,
    associated_user: null,
  },
  {
    id: "4DEBD0CBB5C861CB",
    name: "Santander - Financeira",
    client_code: "7015",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 155,
    associated_user: null,
  },
  {
    id: "82D8653C9AD89CDE",
    name: "TesteMassivoAPI",
    client_code: "TesteMassivoAPI",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "00C8C09A0CC166DA",
    name: "BV Bom Pagador",
    client_code: "7011",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 18153,
    associated_user: null,
  },
  {
    id: "65B7600E4461D2ED",
    name: "BV ADM",
    client_code: "7012",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 8709,
    associated_user: null,
  },
  {
    id: "AE1B2230C4E3479E",
    name: "BV ADM Reneg",
    client_code: "7013",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 5736,
    associated_user: null,
  },
  {
    id: "BC6FEDED863810D3",
    name: "Teste Ivan",
    client_code: "",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "730D81C464C317A6",
    name: "Carteiro Itaú Cartões",
    client_code: "7014",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 14311,
    associated_user: null,
  },
  {
    id: "F8B92F387FC36C79",
    name: "Itaú PF Portal",
    client_code: "7016",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 2,
    associated_user: null,
  },
  {
    id: "A8649A1C34581D02",
    name: "Itaú Cartões Portal",
    client_code: "7017",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "4C9BDB91AF0504CB",
    name: "Itaú Phygital Portal",
    client_code: "7018",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "9E7BFC879AC9CA43",
    name: "Carteiro Santander Financeira",
    client_code: "7019",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 39,
    associated_user: null,
  },
  {
    id: "DA7D9AA96D4636C2",
    name: "Itaú Personnalite",
    client_code: "7020",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1725,
    associated_user: null,
  },
  {
    id: "08EF73F913768414",
    name: "Itaú PF 2",
    client_code: "7085",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 5688,
    associated_user: null,
  },
  {
    id: "C3668AC366C19F55",
    name: "Itaú PF 3",
    client_code: "7042",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 4813,
    associated_user: null,
  },
  {
    id: "DA3A3242975CC5A7",
    name: "Itaú PF 4",
    client_code: "7043",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 6394,
    associated_user: null,
  },
  {
    id: "DD46FADFC45EC419",
    name: "Itaú PF 5",
    client_code: "7044",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 8646,
    associated_user: null,
  },
  {
    id: "A29B7C5A6265DB28",
    name: "Itaú ACC 2",
    client_code: "7093",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 70,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 5445,
    associated_user: null,
  },
  {
    id: "279D375B1F94AE37",
    name: "Itaú ACC 3",
    client_code: "7095",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 70,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 6985,
    associated_user: null,
  },
  {
    id: "058D21852D21B1CD",
    name: "Itaú ACC 5",
    client_code: "7119",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 70,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1417,
    associated_user: null,
  },
  {
    id: "D083142DF80F8C56",
    name: "Itaú ACC 4",
    client_code: "7099",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 70,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 7546,
    associated_user: null,
  },
  {
    id: "8A80865830C21E76",
    name: "BV Bom Pagador 2",
    client_code: "7037",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 5876,
    associated_user: null,
  },
  {
    id: "AB5422E793C54D17",
    name: "BV ADM 2",
    client_code: "7092",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 2888,
    associated_user: null,
  },
  {
    id: "EB091C17E0278FF8",
    name: "BV ADM Reneg 2",
    client_code: "7090",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 137,
    associated_user: null,
  },
  {
    id: "74ECFE4B90F2C536",
    name: "Itaú Veiculos",
    client_code: "30",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1349,
    associated_user: null,
  },
  {
    id: "B39FBA1C78F0C97D",
    name: "Itaú Imobiliario",
    client_code: "7021",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 14,
    associated_user: null,
  },
  {
    id: "9CEEB1359860A0B3",
    name: "Itaú PJ",
    client_code: "57",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1042,
    associated_user: null,
  },
  {
    id: "22B016CA1CF2A324",
    name: "Itaú Veiculos 2",
    client_code: "7050",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 730,
    associated_user: null,
  },
  {
    id: "2E857E705BEDCDBE",
    name: "Carteiro Itaú PF",
    client_code: "7022",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "1BC4AB9886644E36",
    name: "Carteiro Itaú PF Colchão",
    client_code: "7023",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 310,
    associated_user: null,
  },
  {
    id: "7532AC2EE99D00EC",
    name: "Carteiro Itaú Cartões Colchão",
    client_code: "7025",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 513,
    associated_user: null,
  },
  {
    id: "AB6595C81CFED4BB",
    name: "Carteiro Itaú Phygital BPF",
    client_code: "7026",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "4268CB7A96295AD6",
    name: "Carteiro Itaú PJ",
    client_code: "7027",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 2,
    associated_user: null,
  },
  {
    id: "927C5F485CAA17D9",
    name: "Carteiro Itaú Veículos",
    client_code: "7028",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "06676EAA7910CF6D",
    name: "Carteiro Itaú Imobiliário",
    client_code: "7029",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "0BCE91C558A4E086",
    name: "Carteiro Itaú IC",
    client_code: "7030",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "FFEC6DAE5C1DB601",
    name: "Carteiro Itaú CDC",
    client_code: "7031",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "BAADB6B52F61EC02",
    name: "Carteiro Itaú Personnalite",
    client_code: "7032",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "7C59CDB504181827",
    name: "Carteiro Bradesco Comercial",
    client_code: "7033",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "1B0602A0075C8482",
    name: "Carteiro Bradesco Digital",
    client_code: "7034",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "0893EE7E73AF65DC",
    name: "Carteiro Bradesco Veículos",
    client_code: "7035",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "184A465E82C0829A",
    name: "Carteiro Bradesco LP",
    client_code: "7036",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "F5F6FA66DE8E4A91",
    name: "Carteiro Bradesco Telecobranca",
    client_code: "7102",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "B4D9B7DAAD8EC68E",
    name: "Carteiro BRADESCO - ALTOS VALORES",
    client_code: "7083",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "5320EAAE84DB9AE9",
    name: "Carteiro NUBANK ATIVO - VAREJO",
    client_code: "7040",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 460,
    associated_user: null,
  },
  {
    id: "10DA92C9E133E2C7",
    name: "Carteiro NUBANK DI - VAREJO",
    client_code: "7041",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "B88E5BFFA472886D",
    name: "Carteiro NUBANK EMPRÉSTIMOS - VAREJO",
    client_code: "7084",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "F57FFAE8934ABF43",
    name: "Carteiro SANTANDER - FINANCEIRA",
    client_code: "7086",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "8474047ACA81CAC6",
    name: "Carteiro C6 Bank",
    client_code: "7103",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "3A28D6480385C557",
    name: "Carteiro C6 Auto",
    client_code: "7087",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "1B35FDCAAA610DFC",
    name: "Carteiro Recovery",
    client_code: "7045",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "6D43989540114DE7",
    name: "Carteiro Volkswagen",
    client_code: "7088",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "1B42550CDB34BF33",
    name: "Carteiro PAN - RETOMADOS",
    client_code: "7047",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "C8C8A00C7B07C1AF",
    name: "Carteiro PAN - VAREJO",
    client_code: "7048",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "A6D7EE89F472CFE2",
    name: "Carteiro PAN ATIVOS - COBRANÇA",
    client_code: "7049",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "4F6059B3B47DF5F6",
    name: "Carteiro Pan Encerramentos",
    client_code: "7096",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "9609B4C6CE4582AE",
    name: "Carteiro Pan Cartões 2.0",
    client_code: "7051",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "5EC021C2CFC08822",
    name: "Carteiro PAN WO - COBRANÇA",
    client_code: "7052",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 2,
    associated_user: null,
  },
  {
    id: "7314B6F3D7D4F687",
    name: "Carteiro PAN AJUIZADOS - COBRANÇA",
    client_code: "7053",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "DFFC16847B9456B1",
    name: "Carteiro PAN - CONTACT",
    client_code: "7054",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "D768C8A02F51C203",
    name: "Carteiro Pan Imobiliário",
    client_code: "7055",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "3E6F529849E85FDA",
    name: "Carteiro Pan Consórcio",
    client_code: "7056",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "DD92D04E14AE42D2",
    name: "Carteiro Pan Cartões",
    client_code: "7057",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "C4E7CC55D27C2D82",
    name: "Carteiro Pan Cartão Ativo ",
    client_code: "7058",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "F84F9C89556F7C8A",
    name: "Carteiro Pan Limite Emergencial",
    client_code: "7059",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "C963DA98D7C1A22E",
    name: "Carteiro Pan Emprestimo Pessoal",
    client_code: "7060",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "9196162DC1976F75",
    name: "Carteiro Safra",
    client_code: "7061",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1,
    associated_user: null,
  },
  {
    id: "529BC4A26BDBB28D",
    name: "Carteiro Safra Veículos",
    client_code: "7062",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "40243C6D2E6A3A69",
    name: "Carteiro Safra Refin",
    client_code: "7063",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "06F7F0A883CC4994",
    name: "Carteiro Safra BS Grupo 2",
    client_code: "7064",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "FB98F0A117EFF8F3",
    name: "Carteiro Safra BS Grupo 1",
    client_code: "7065",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "C86D7AB95E8B630B",
    name: "Carteiro Safra Saldo Remanescente",
    client_code: "7066",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "B5165763EA7D3743",
    name: "Carteiro SAFRA CARTÕES - VAREJO",
    client_code: "7067",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "B6D3D758FE01F290",
    name: "Carteiro Porto Seguro",
    client_code: "7068",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "98F6EEA55D01ADC2",
    name: "Carteiro Inter",
    client_code: "7069",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "6099786721673874",
    name: "Carteiro BMG",
    client_code: "7070",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "BE6458882281A828",
    name: "Carteiro BANCO DO BRASIL - VEÍCULOS",
    client_code: "7071",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "5E872A38986D22AD",
    name: "Carteiro PICPAY - VAREJO",
    client_code: "7072",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "1B464407E2C39744",
    name: "Carteiro ARC4U - SECURITIZADORA",
    client_code: "7073",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "77A7CB40D1B0C429",
    name: "Carteiro MAGALU - VAREJO",
    client_code: "7074",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "5AFF3A2E4058CD1A",
    name: "Carteiro MÉLIUZ - VAREJO",
    client_code: "7075",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "ACCC3E2DFBB0F039",
    name: "Carteiro RENNER - VAREJO",
    client_code: "7076",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "9C87C8D17E7FF90F",
    name: "Carteiro RETURN - SECURITIZADORA",
    client_code: "7077",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "AED3089A16C866F2",
    name: "Carteiro VIA VAREJO",
    client_code: "7078",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "6CA19FCE423AAE83",
    name: "Carteiro DIVZERO - SECURITIZADORA",
    client_code: "7079",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "3BA3DD575C59C3EC",
    name: "Carteiro ITAPEVA - SECURITIZADORA",
    client_code: "7080",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "F20A60377CA282F7",
    name: "Carteiro CETELEM - VAREJO",
    client_code: "7081",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "D10B361D1CACB565",
    name: "Carteiro Mercantil",
    client_code: "7082",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "A55F764ED661A4F3",
    name: "BV Juridico Contencioso IPF 1",
    client_code: "7046",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1,
    associated_user: null,
  },
  {
    id: "BD22788BD2927404",
    name: "Carteiro BV WO",
    client_code: "6008",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "5D107DC8D09B23DB",
    name: "AGV - Nubank",
    client_code: "7038",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 15,
    associated_user: null,
  },
  {
    id: "8883EE021246655A",
    name: "Carteiro BV Bom Pagador",
    client_code: "6001",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 304,
    associated_user: null,
  },
  {
    id: "A4C057CC48F81112",
    name: "Carteiro BV Reneg ADM",
    client_code: "6003",
    status: true,
    show_chat: false,
    distribution_method: "1",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 10,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 625,
    associated_user: null,
  },
  {
    id: "1130882349051DD6",
    name: "BV Juridico Contencioso IPF 2",
    client_code: "7089",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "D654AE21B3166122",
    name: "BV Juridico Contencioso IPF 3",
    client_code: "7091",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "A228842638E689A3",
    name: "BV Juridico Contencioso IPF 4",
    client_code: "7094",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "A268C9A166B175F7",
    name: "BV WO 1",
    client_code: "7097",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1,
    associated_user: null,
  },
  {
    id: "679D02A77FA4E99E",
    name: "BV WO 2",
    client_code: "7098",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 1,
    associated_user: null,
  },
  {
    id: "07F4ED83DE2102F0",
    name: "BV WO 3",
    client_code: "7100",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "120D18A8F4817467",
    name: "BV WO 4",
    client_code: "7101",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "26966B2C6AA7603F",
    name: "Carteiro BVCL",
    client_code: "6004",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "8C1EC770BFC67EE4",
    name: "Carteiro BV CA",
    client_code: "6005",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "764EE9A7C1B4A67B",
    name: "Carteiro BV CP",
    client_code: "6006",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "C7749E0EEE63C2DA",
    name: "Carteiro BV Juridico Contencioso IPF",
    client_code: "6007",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "1715AC5DE14EB1B2",
    name: "Carteiro BV NEON",
    client_code: "6009",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "ECD9880D622F111C",
    name: "Carteiro BV Solar ",
    client_code: "6010",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "DF6E9BD31D6C53D8",
    name: "Carteiro BV CONSIGNADO - VAREJO",
    client_code: "6011",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
  {
    id: "7DA5676A4035AFD9",
    name: "Carteiro BV - DESAVERBADO",
    client_code: "6012",
    status: true,
    show_chat: false,
    distribution_method: "2",
    number_loyal_customers_online: null,
    number_loyal_customers_offline: null,
    term_Idr: "",
    idr_return_time: 60,
    idr_wait_time_operation_type: 1,
    idr_wait_time_go_to_idr_id: "",
    idr_wait_time_go_to_idr_step_name: "",
    contacts_amount: 0,
    associated_user: null,
  },
];
for (let i = 0; i < Robbu.length; i++) {
  const element = Robbu[i];
  console.log(`${element.name};${element.client_code}`);
}

let Radar = [
  {
    idGrupo: 198,
    nome: "BpMessage",
    cdGrupo: 999,
    idFornecedor: 18,
    idCarteira: 70,
    nomeCarteira: "BpMessage",
    idSistema: 0,
  },
  {
    idGrupo: 199,
    nome: "ITAU CARTOES VAREJO",
    cdGrupo: 51,
    idFornecedor: 18,
    idCarteira: 51,
    nomeCarteira: "Revenda",
    idSistema: 0,
  },
  {
    idGrupo: 200,
    nome: "ITAU CARTOES COLCHAO",
    cdGrupo: 68,
    idFornecedor: 18,
    idCarteira: 62,
    nomeCarteira: "Colchão ACC",
    idSistema: 0,
  },
  {
    idGrupo: 201,
    nome: "ITAU PF COLCHAO",
    cdGrupo: 66,
    idFornecedor: 18,
    idCarteira: 60,
    nomeCarteira: "Colchão PF",
    idSistema: 0,
  },
  {
    idGrupo: 202,
    nome: "BV - RENEG CONSIGNADO",
    cdGrupo: 16,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 203,
    nome: "BV - DESAVERBADO",
    cdGrupo: 10,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 204,
    nome: "BV CARTÕES AMIGÁVEL - VAREJO",
    cdGrupo: 165,
    idFornecedor: 18,
    idCarteira: 68,
    nomeCarteira: "BV Cartões Amig.",
    idSistema: 0,
  },
  {
    idGrupo: 205,
    nome: "BV CL - VAREJO",
    cdGrupo: 2,
    idFornecedor: 18,
    idCarteira: 64,
    nomeCarteira: "BV Cartões CL",
    idSistema: 0,
  },
  {
    idGrupo: 206,
    nome: "BV CONSIGNADO - VAREJO",
    cdGrupo: 4,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 207,
    nome: "BV CP - VAREJO",
    cdGrupo: 8,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 208,
    nome: "BV WO 1",
    cdGrupo: 7097,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 209,
    nome: "BV - COBRANCA",
    cdGrupo: 12,
    idFornecedor: 18,
    idCarteira: 3,
    nomeCarteira: "BV (BVC)",
    idSistema: 0,
  },
  {
    idGrupo: 210,
    nome: "BV WO - COBRANCA JURIDICA",
    cdGrupo: 19,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 211,
    nome: "BV Juridico Contencioso IPF 1",
    cdGrupo: 7046,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 212,
    nome: "Carteiro Digital BVC",
    cdGrupo: 77,
    idFornecedor: 18,
    idCarteira: 3,
    nomeCarteira: "BV (BVC)",
    idSistema: 0,
  },
  {
    idGrupo: 213,
    nome: "PAN CARTOES",
    cdGrupo: 137,
    idFornecedor: 18,
    idCarteira: 7,
    nomeCarteira: "Pan Cartões",
    idSistema: 0,
  },
  {
    idGrupo: 214,
    nome: "PAN COBRANCA",
    cdGrupo: 36,
    idFornecedor: 18,
    idCarteira: 4,
    nomeCarteira: "Pan Veiculos",
    idSistema: 0,
  },
  {
    idGrupo: 215,
    nome: "Bradesco Comercial",
    cdGrupo: 161,
    idFornecedor: 18,
    idCarteira: 44,
    nomeCarteira: "Bradesco Comercial",
    idSistema: 0,
  },
  {
    idGrupo: 216,
    nome: "BV IPF",
    cdGrupo: 49,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 217,
    nome: "ITAU PF CENTRAL COLCHAO",
    cdGrupo: 84,
    idFornecedor: 18,
    idCarteira: 77,
    nomeCarteira: "Varejo PF Central (ColchÃ£o)",
    idSistema: 0,
  },
  {
    idGrupo: 218,
    nome: "ITAU VEICULOS",
    cdGrupo: 30,
    idFornecedor: 18,
    idCarteira: 50,
    nomeCarteira: "Itau",
    idSistema: 0,
  },
  {
    idGrupo: 219,
    nome: "ITAU PJ CENTRAL",
    cdGrupo: 182,
    idFornecedor: 18,
    idCarteira: 74,
    nomeCarteira: "Itau PJ Central",
    idSistema: 0,
  },
  {
    idGrupo: 220,
    nome: "Recovery",
    cdGrupo: 61,
    idFornecedor: 18,
    idCarteira: 2,
    nomeCarteira: "RECOVERY",
    idSistema: 0,
  },
  {
    idGrupo: 221,
    nome: "Itaú PJ",
    cdGrupo: 57,
    idFornecedor: 18,
    idCarteira: 59,
    nomeCarteira: "ItauPJ",
    idSistema: 0,
  },
  {
    idGrupo: 222,
    nome: "ITAU IC",
    cdGrupo: 69,
    idFornecedor: 18,
    idCarteira: 33,
    nomeCarteira: "Magazine Luiza",
    idSistema: 0,
  },
  {
    idGrupo: 223,
    nome: "BRADESCO VAREJO LP",
    cdGrupo: 13,
    idFornecedor: 18,
    idCarteira: 1,
    nomeCarteira: "BRADESCO VAREJO",
    idSistema: 0,
  },
  {
    idGrupo: 224,
    nome: "Itaú ACC",
    cdGrupo: 7005,
    idFornecedor: 18,
    idCarteira: 56,
    nomeCarteira: "Varejo ACC",
    idSistema: 0,
  },
  {
    idGrupo: 225,
    nome: "Bradesco LP",
    cdGrupo: 7002,
    idFornecedor: 18,
    idCarteira: 1,
    nomeCarteira: "BRADESCO VAREJO",
    idSistema: 0,
  },
  {
    idGrupo: 226,
    nome: "Safra",
    cdGrupo: 7001,
    idFornecedor: 18,
    idCarteira: 9,
    nomeCarteira: "Safra",
    idSistema: 0,
  },
  {
    idGrupo: 227,
    nome: "Itaú PF",
    cdGrupo: 7004,
    idFornecedor: 18,
    idCarteira: 55,
    nomeCarteira: "Varejo",
    idSistema: 0,
  },
  {
    idGrupo: 238,
    nome: "PHYGITAL",
    cdGrupo: 7010,
    idFornecedor: 18,
    idCarteira: 79,
    nomeCarteira: "PHYGITAL",
    idSistema: 0,
  },
  {
    idGrupo: 275,
    nome: "Itaú Phygital PF",
    cdGrupo: 7006,
    idFornecedor: 18,
    idCarteira: 79,
    nomeCarteira: "PHYGITAL",
    idSistema: 0,
  },
  {
    idGrupo: 311,
    nome: "ITAU PJ COBRANÇA",
    cdGrupo: 57,
    idFornecedor: 18,
    idCarteira: 59,
    nomeCarteira: "ItauPJ",
    idSistema: 0,
  },
  {
    idGrupo: 340,
    nome: "Bradesco Phygital",
    cdGrupo: 7008,
    idFornecedor: 18,
    idCarteira: 44,
    nomeCarteira: "Bradesco Comercial",
    idSistema: 0,
  },
  {
    idGrupo: 697,
    nome: "BV Bom pagador",
    cdGrupo: 7011,
    idFornecedor: 18,
    idCarteira: 3,
    nomeCarteira: "BV (BVC)",
    idSistema: 0,
  },
  {
    idGrupo: 698,
    nome: "BV ADM",
    cdGrupo: 7012,
    idFornecedor: 18,
    idCarteira: 3,
    nomeCarteira: "BV (BVC)",
    idSistema: 0,
  },
  {
    idGrupo: 699,
    nome: "BV ADM Reneg",
    cdGrupo: 7013,
    idFornecedor: 18,
    idCarteira: 3,
    nomeCarteira: "BV (BVC)",
    idSistema: 0,
  },
  {
    idGrupo: 740,
    nome: "Carteiro Digital BVC 2",
    cdGrupo: 78,
    idFornecedor: 18,
    idCarteira: 3,
    nomeCarteira: "BV (BVC)",
    idSistema: 0,
  },
  {
    idGrupo: 741,
    nome: "Carteiro Digital BVC - 3",
    cdGrupo: 79,
    idFornecedor: 18,
    idCarteira: 3,
    nomeCarteira: "BV (BVC)",
    idSistema: 0,
  },
  {
    idGrupo: 775,
    nome: "Carteiro Digital ITAÙ Cartões",
    cdGrupo: 7014,
    idFornecedor: 18,
    idCarteira: 56,
    nomeCarteira: "Varejo ACC",
    idSistema: 0,
  },
  {
    idGrupo: 776,
    nome: "Santander - Financeira",
    cdGrupo: 7015,
    idFornecedor: 18,
    idCarteira: 120,
    nomeCarteira: "Santander Cartões",
    idSistema: 0,
  },
  {
    idGrupo: 779,
    nome: "Itaú PF Portal",
    cdGrupo: 7016,
    idFornecedor: 18,
    idCarteira: 55,
    nomeCarteira: "Varejo",
    idSistema: 0,
  },
  {
    idGrupo: 780,
    nome: "Itaú Cartões Portal",
    cdGrupo: 7017,
    idFornecedor: 18,
    idCarteira: 56,
    nomeCarteira: "Varejo ACC",
    idSistema: 0,
  },
  {
    idGrupo: 781,
    nome: "Itaú Phygital Portal",
    cdGrupo: 7018,
    idFornecedor: 18,
    idCarteira: 79,
    nomeCarteira: "PHYGITAL",
    idSistema: 0,
  },
  {
    idGrupo: 787,
    nome: "Carteiro Santander Financeira",
    cdGrupo: 7019,
    idFornecedor: 18,
    idCarteira: 120,
    nomeCarteira: "Santander Cartões",
    idSistema: 0,
  },
  {
    idGrupo: 788,
    nome: "Itaú Personnalite",
    cdGrupo: 7020,
    idFornecedor: 18,
    idCarteira: 133,
    nomeCarteira: "Itaú Personnalite",
    idSistema: 0,
  },
  {
    idGrupo: 789,
    nome: "Itaú Imobiliario",
    cdGrupo: 7021,
    idFornecedor: 18,
    idCarteira: 57,
    nomeCarteira: "Imobiliário",
    idSistema: 0,
  },
  {
    idGrupo: 798,
    nome: "Carteiro Itaú PF",
    cdGrupo: 7022,
    idFornecedor: 18,
    idCarteira: 117,
    nomeCarteira: "Itau PF",
    idSistema: 0,
  },
  {
    idGrupo: 799,
    nome: "Carteiro Itaú PF Colchão",
    cdGrupo: 7023,
    idFornecedor: 18,
    idCarteira: 60,
    nomeCarteira: "Colchão PF",
    idSistema: 0,
  },
  {
    idGrupo: 800,
    nome: "Carteiro Itaú Cartões",
    cdGrupo: 7014,
    idFornecedor: 18,
    idCarteira: 56,
    nomeCarteira: "Varejo ACC",
    idSistema: 0,
  },
  {
    idGrupo: 801,
    nome: "Carteiro Itaú Cartões Colchão",
    cdGrupo: 7025,
    idFornecedor: 18,
    idCarteira: 62,
    nomeCarteira: "Colchão ACC",
    idSistema: 0,
  },
  {
    idGrupo: 802,
    nome: "Carteiro Itaú Phygital BPF",
    cdGrupo: 7026,
    idFornecedor: 18,
    idCarteira: 79,
    nomeCarteira: "PHYGITAL",
    idSistema: 0,
  },
  {
    idGrupo: 803,
    nome: "Carteiro Itaú PJ",
    cdGrupo: 7027,
    idFornecedor: 18,
    idCarteira: 59,
    nomeCarteira: "ItauPJ",
    idSistema: 0,
  },
  {
    idGrupo: 804,
    nome: "Carteiro Itaú Veículos",
    cdGrupo: 7028,
    idFornecedor: 18,
    idCarteira: 99,
    nomeCarteira: "Itau Veículos ",
    idSistema: 0,
  },
  {
    idGrupo: 805,
    nome: "Carteiro Itaú Imobiliário",
    cdGrupo: 7029,
    idFornecedor: 18,
    idCarteira: 57,
    nomeCarteira: "Imobiliário",
    idSistema: 0,
  },
  {
    idGrupo: 806,
    nome: "Carteiro BMG",
    cdGrupo: 7030,
    idFornecedor: 18,
    idCarteira: 61,
    nomeCarteira: "Itau IC - BMG",
    idSistema: 0,
  },
  {
    idGrupo: 807,
    nome: "Carteiro Itaú CDC",
    cdGrupo: 7031,
    idFornecedor: 18,
    idCarteira: 67,
    nomeCarteira: "CDC",
    idSistema: 0,
  },
  {
    idGrupo: 808,
    nome: "Carteiro Itaú Personnalite",
    cdGrupo: 7032,
    idFornecedor: 18,
    idCarteira: 133,
    nomeCarteira: "Itaú Personnalite",
    idSistema: 0,
  },
  {
    idGrupo: 809,
    nome: "Carteiro Bradesco Comercial",
    cdGrupo: 7033,
    idFornecedor: 18,
    idCarteira: 44,
    nomeCarteira: "Bradesco Comercial",
    idSistema: 0,
  },
  {
    idGrupo: 810,
    nome: "Carteiro Bradesco Digital",
    cdGrupo: 7034,
    idFornecedor: 18,
    idCarteira: 128,
    nomeCarteira: "Bradesco - Digital",
    idSistema: 0,
  },
  {
    idGrupo: 811,
    nome: "Carteiro Bradesco Veículos",
    cdGrupo: 7035,
    idFornecedor: 18,
    idCarteira: 78,
    nomeCarteira: "BRADESCO - COBRANÇA",
    idSistema: 0,
  },
  {
    idGrupo: 812,
    nome: "Carteiro Bradesco LP",
    cdGrupo: 7036,
    idFornecedor: 18,
    idCarteira: 1,
    nomeCarteira: "BRADESCO VAREJO",
    idSistema: 0,
  },
  {
    idGrupo: 813,
    nome: "BV Bom Pagador 2",
    cdGrupo: 7037,
    idFornecedor: 18,
    idCarteira: 3,
    nomeCarteira: "BV (BVC)",
    idSistema: 0,
  },
  {
    idGrupo: 814,
    nome: "AGV - Nubank",
    cdGrupo: 7038,
    idFornecedor: 18,
    idCarteira: 132,
    nomeCarteira: "Nubank - Cancelado",
    idSistema: 0,
  },
  {
    idGrupo: 820,
    nome: "Carteiro BV Reneg ADM",
    cdGrupo: 6003,
    idFornecedor: 18,
    idCarteira: 3,
    nomeCarteira: "BV (BVC)",
    idSistema: 0,
  },
  {
    idGrupo: 821,
    nome: "Carteiro Bom Pagador",
    cdGrupo: 6001,
    idFornecedor: 18,
    idCarteira: 3,
    nomeCarteira: "BV (BVC)",
    idSistema: 0,
  },
  {
    idGrupo: 822,
    nome: "Itaú PF 2",
    cdGrupo: 7085,
    idFornecedor: 18,
    idCarteira: 55,
    nomeCarteira: "Varejo",
    idSistema: 0,
  },
  {
    idGrupo: 823,
    nome: "Itaú PF 3",
    cdGrupo: 7042,
    idFornecedor: 18,
    idCarteira: 55,
    nomeCarteira: "Varejo",
    idSistema: 0,
  },
  {
    idGrupo: 824,
    nome: "Itaú PF 4",
    cdGrupo: 7043,
    idFornecedor: 18,
    idCarteira: 55,
    nomeCarteira: "Varejo",
    idSistema: 0,
  },
  {
    idGrupo: 825,
    nome: "Itaú PF 5",
    cdGrupo: 7044,
    idFornecedor: 18,
    idCarteira: 55,
    nomeCarteira: "Varejo",
    idSistema: 0,
  },
  {
    idGrupo: 826,
    nome: "AGV - Itaú PF",
    cdGrupo: 7045,
    idFornecedor: 18,
    idCarteira: 55,
    nomeCarteira: "Varejo",
    idSistema: 0,
  },
  {
    idGrupo: 827,
    nome: "AGV - Itaú ACC",
    cdGrupo: 7046,
    idFornecedor: 18,
    idCarteira: 56,
    nomeCarteira: "Varejo ACC",
    idSistema: 0,
  },
  {
    idGrupo: 828,
    nome: "BV ADM Reneg 2",
    cdGrupo: 7090,
    idFornecedor: 18,
    idCarteira: 3,
    nomeCarteira: "BV (BVC)",
    idSistema: 0,
  },
  {
    idGrupo: 830,
    nome: "BV ADM\t2",
    cdGrupo: 7092,
    idFornecedor: 18,
    idCarteira: 3,
    nomeCarteira: "BV (BVC)",
    idSistema: 0,
  },
  {
    idGrupo: 832,
    nome: "Itaú Veiculos 2",
    cdGrupo: 7050,
    idFornecedor: 18,
    idCarteira: 99,
    nomeCarteira: "Itau Veículos ",
    idSistema: 0,
  },
  {
    idGrupo: 833,
    nome: "BV Juridico Contencioso IPF 2",
    cdGrupo: 7089,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 834,
    nome: "BV Juridico Contencioso IPF 3",
    cdGrupo: 7091,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 835,
    nome: "BV Juridico Contencioso IPF 4",
    cdGrupo: 7094,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 836,
    nome: "BV WO 2",
    cdGrupo: 7019,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 837,
    nome: "BV WO 3",
    cdGrupo: 7100,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 838,
    nome: "BV WO 4",
    cdGrupo: 7101,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 839,
    nome: "Carteiro BV CP",
    cdGrupo: 6006,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 840,
    nome: "Carteiro BV - DESAVERBADO",
    cdGrupo: 6012,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 841,
    nome: "BV - SOLAR",
    cdGrupo: 18,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 842,
    nome: "C6 BANK - VEÍCULOS",
    cdGrupo: 100,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 843,
    nome: "Carteiro ARC4U - SECURITIZADORA",
    cdGrupo: 7073,
    idFornecedor: 18,
    idCarteira: 137,
    nomeCarteira: "ARC4U BTG Pactual",
    idSistema: 0,
  },
  {
    idGrupo: 844,
    nome: "Carteiro BANCO DO BRASIL - VEÍCULOS",
    cdGrupo: 7071,
    idFornecedor: 18,
    idCarteira: 8,
    nomeCarteira: "Banco do Brasil",
    idSistema: 0,
  },
  {
    idGrupo: 845,
    nome: "Carteiro BRADESCO - ALTOS VALORES",
    cdGrupo: 7083,
    idFornecedor: 18,
    idCarteira: 44,
    nomeCarteira: "Bradesco Comercial",
    idSistema: 0,
  },
  {
    idGrupo: 846,
    nome: "Carteiro Bradesco Telecobranca",
    cdGrupo: 7102,
    idFornecedor: 18,
    idCarteira: 134,
    nomeCarteira: "Bradesco - Telecobrança Banco",
    idSistema: 0,
  },
  {
    idGrupo: 847,
    nome: "Carteiro BV ADM",
    cdGrupo: 6002,
    idFornecedor: 18,
    idCarteira: 3,
    nomeCarteira: "BV (BVC)",
    idSistema: 0,
  },
  {
    idGrupo: 848,
    nome: "Carteiro BV CA",
    cdGrupo: 6005,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 849,
    nome: "Carteiro BV CONSIGNADO - VAREJO",
    cdGrupo: 6011,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 850,
    nome: "Carteiro BV Juridico Contencioso IPF",
    cdGrupo: 6007,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 851,
    nome: "Carteiro BV NEON",
    cdGrupo: 6009,
    idFornecedor: 18,
    idCarteira: 19,
    nomeCarteira: "BV (BpCob)",
    idSistema: 0,
  },
  {
    idGrupo: 852,
    nome: "Itaú ACC 2",
    cdGrupo: 7093,
    idFornecedor: 18,
    idCarteira: 56,
    nomeCarteira: "Varejo ACC",
    idSistema: 0,
  },
  {
    idGrupo: 853,
    nome: "Itaú ACC 3",
    cdGrupo: 7095,
    idFornecedor: 18,
    idCarteira: 56,
    nomeCarteira: "Varejo ACC",
    idSistema: 0,
  },
  {
    idGrupo: 854,
    nome: "Itaú ACC 4",
    cdGrupo: 7099,
    idFornecedor: 18,
    idCarteira: 56,
    nomeCarteira: "Varejo ACC",
    idSistema: 0,
  },
  {
    idGrupo: 855,
    nome: "Itaú ACC 5",
    cdGrupo: 7119,
    idFornecedor: 18,
    idCarteira: 56,
    nomeCarteira: "Varejo ACC",
    idSistema: 0,
  },
];
for (let i = 0; i < Radar.length; i++) {
  const element = Radar[i];
  console.log(`${element.nome};${element.cdGrupo}`);
}
